/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.thirdo;

public final class R {
    public static final class array {
        public static final int qubits=0x7f060000;
    }
    public static final class attr {
    }
    public static final class dimen {
        /** 
         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f040001;
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public static final int gateDim=0x7f040000;
    }
    public static final class drawable {
        public static final int blue_ball=0x7f020000;
        public static final int c=0x7f020001;
        public static final int cnot=0x7f020002;
        public static final int cnot1=0x7f020003;
        public static final int cnot2=0x7f020004;
        public static final int cswap=0x7f020005;
        public static final int evaluate=0x7f020006;
        public static final int fredkin=0x7f020007;
        public static final int h=0x7f020008;
        public static final int ic_launcher=0x7f020009;
        public static final int line=0x7f02000a;
        public static final int q0=0x7f02000b;
        public static final int q1=0x7f02000c;
        public static final int swap=0x7f02000d;
        public static final int swap1=0x7f02000e;
        public static final int swap2=0x7f02000f;
        public static final int toffoli=0x7f020010;
        public static final int tp=0x7f020011;
        public static final int x=0x7f020012;
        public static final int y=0x7f020013;
        public static final int z=0x7f020014;
    }
    public static final class id {
        public static final int action_settings=0x7f090016;
        public static final int bottom_container=0x7f09000e;
        public static final int bottom_container2=0x7f09000f;
        public static final int bottom_container3=0x7f090010;
        public static final int bottom_container4=0x7f090011;
        public static final int bottom_container5=0x7f090012;
        public static final int bottom_container6=0x7f090013;
        public static final int buttonBar=0x7f090006;
        public static final int compiledGates=0x7f090003;
        public static final int horizontalScrollView1=0x7f09000d;
        public static final int imageButton1=0x7f090004;
        public static final int imageButton2=0x7f090005;
        public static final int listView1=0x7f090015;
        public static final int qubitButton1=0x7f090007;
        public static final int qubitButton2=0x7f090008;
        public static final int qubitButton3=0x7f090009;
        public static final int qubitButton4=0x7f09000a;
        public static final int qubitButton5=0x7f09000b;
        public static final int qubitButton6=0x7f09000c;
        public static final int result=0x7f090014;
        public static final int spinner1=0x7f090002;
        public static final int topCont=0x7f090001;
        public static final int topest=0x7f090000;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int result=0x7f030001;
    }
    public static final class menu {
        public static final int main=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int comp=0x7f050004;
        public static final int desc=0x7f050002;
        public static final int eval=0x7f050003;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
    }
}
